services:
    learning:
        image: learning:latest
        build:
            context: .
        ports:
            - target: 3000
              published: 3000
              protocol: tcp
              mode: host
